export const sectionCategories = {
  gastronomy: [
    { label: "Abierto ahora", desc: "Locales disponibles hoy", href: "/negocios?abierto=true", bg: "bg-brand-earth/10", color: "text-brand-earth" },
    { label: "Bar/Café", desc: "Tragos, café y más", href: "/negocios?categoria=cafe_bar", bg: "bg-brand-earth/10", color: "text-brand-earth" },
    { label: "Delivery", desc: "Pedidos a domicilio", href: "/negocios?delivery=true", bg: "bg-brand-pine/10", color: "text-brand-pine" },
    { label: "Take Away", desc: "Pedí y retirá en el local", href: "/negocios?takeaway=true", bg: "bg-brand-slate/10", color: "text-brand-slate" },
    { label: "Restaurantes", desc: "Cocina regional y menú del día", href: "/negocios?categoria=restaurant", bg: "bg-brand-earth/10", color: "text-brand-earth" },
    { label: "Viandas", desc: "Comida casera para llevar", href: "/negocios?categoria=viandas", bg: "bg-brand-slate/10", color: "text-brand-slate" },
    { label: "Panadería", desc: "Pan, facturas y productos de horno", href: "/negocios?categoria=panaderia", bg: "bg-brand-earth/10", color: "text-brand-earth" },
    { label: "Varios", desc: "Otros locales gastronómicos", href: "/negocios?categoria=other", bg: "bg-brand-sand/50", color: "text-brand-charcoal" },
    { label: "Todos", desc: "Ver toda la gastronomía", href: "/negocios", bg: "bg-brand-sand/50", color: "text-brand-charcoal" },
  ],
  services: [
    { label: "Alarmas-Seguridad", desc: "Sistemas de alarmas y seguridad", href: "/directorio/services?cat=alarmas", bg: "bg-brand-slate/10", color: "text-brand-slate" },
    { label: "Cerrajero", desc: "Cerraduras y llaves", href: "/directorio/services?cat=cerrajero", bg: "bg-brand-slate/10", color: "text-brand-slate" },
    { label: "Construcción", desc: "Albañilería y reformas", href: "/directorio/services?cat=construccion", bg: "bg-brand-earth/10", color: "text-brand-earth" },
    { label: "Desinfecciones", desc: "Plagas y fumigaciones", href: "/directorio/services?cat=desinfecciones", bg: "bg-brand-pine/10", color: "text-brand-pine" },
    { label: "Electricidad", desc: "Electricistas matriculados", href: "/directorio/services?cat=electricidad", bg: "bg-brand-slate/10", color: "text-brand-slate" },
    { label: "Fletes", desc: "Transporte de cargas y mudanzas", href: "/directorio/services?cat=fletes", bg: "bg-brand-earth/10", color: "text-brand-earth" },
    { label: "Gasista", desc: "Instalaciones de gas", href: "/directorio/services?cat=gasista", bg: "bg-brand-earth/10", color: "text-brand-earth" },
    { label: "Herrero", desc: "Herrería y soldadura", href: "/directorio/services?cat=herrero", bg: "bg-brand-charcoal/10", color: "text-brand-charcoal" },
    { label: "Impermeabilizaciones", desc: "Techos, paredes y terrazas", href: "/directorio/services?cat=impermeabilizaciones", bg: "bg-brand-pine/10", color: "text-brand-pine" },
    { label: "Paisajismo y Jardines", desc: "Diseño y mantenimiento", href: "/directorio/services?cat=jardinero", bg: "bg-brand-pine/10", color: "text-brand-pine" },
    { label: "Limpieza", desc: "Servicio doméstico", href: "/directorio/services?cat=limpieza", bg: "bg-brand-slate/10", color: "text-brand-slate" },
    { label: "Mecánica", desc: "Talleres y gomería", href: "/directorio/services?cat=mecanica", bg: "bg-brand-charcoal/10", color: "text-brand-charcoal" },
    { label: "Movimiento de suelos", desc: "Excavaciones y nivelaciones", href: "/directorio/services?cat=movimiento", bg: "bg-brand-earth/10", color: "text-brand-earth" },
    { label: "Perforaciones", desc: "Pozos de agua", href: "/directorio/services?cat=perforaciones", bg: "bg-brand-pine/10", color: "text-brand-pine" },
    { label: "Piletero", desc: "Piletas y mantenimiento", href: "/directorio/services?cat=piletero", bg: "bg-brand-slate/10", color: "text-brand-slate" },
    { label: "Pintor", desc: "Pintura interior y exterior", href: "/directorio/services?cat=pintor", bg: "bg-brand-earth/10", color: "text-brand-earth" },
    { label: "Plomería", desc: "Instalaciones y reparaciones", href: "/directorio/services?cat=plomeria", bg: "bg-brand-slate/10", color: "text-brand-slate" },
    { label: "Profesionales", desc: "Contadores, abogados, arquitectos y más", href: "/directorio/services?cat=profesionales", bg: "bg-violet-100", color: "text-violet-700" },
    { label: "Venta de áridos", desc: "Arena, piedra y materiales", href: "/directorio/services?cat=aridos", bg: "bg-brand-slate/10", color: "text-brand-slate" },
    { label: "Zinguero", desc: "Techos y canaletas", href: "/directorio/services?cat=zinguero", bg: "bg-brand-slate/10", color: "text-brand-slate" },
    { label: "Carteles tallados", desc: "Señalética y carteles artesanales", href: "/directorio/services?cat=carteles", bg: "bg-brand-earth/10", color: "text-brand-earth" },
    { label: "Costurera/Modista", desc: "Confección y arreglos de ropa", href: "/directorio/services?cat=costurera", bg: "bg-brand-slate/10", color: "text-brand-slate" },
    { label: "Escuela de Equitación", desc: "Clases y escuelas de equitación", href: "/directorio/services?cat=equitacion", bg: "bg-amber-100", color: "text-amber-700" },
    { label: "Traslados", desc: "Transporte de personas", href: "/directorio/services?cat=traslados", bg: "bg-brand-earth/10", color: "text-brand-earth" },
    { label: "Varios", desc: "Otros servicios del valle", href: "/directorio/services?cat=varios", bg: "bg-brand-sand/50", color: "text-brand-charcoal" },
    { label: "Todos", desc: "Ver todos los servicios", href: "/directorio/services", bg: "bg-brand-sand/50", color: "text-brand-charcoal" },
  ],
  health: [
    { label: "Clínicas y Consultorios", desc: "Atención médica general", href: "/directorio/health?cat=clinicas", bg: "bg-brand-pine/10", color: "text-brand-pine" },
    { label: "Especialidades", desc: "Médicos especializados", href: "/directorio/health?cat=especialidades", bg: "bg-brand-slate/10", color: "text-brand-slate" },
    { label: "Hospitales y Dispensarios", desc: "Guardias y urgencias", href: "/directorio/health?cat=hospitales", bg: "bg-brand-earth/10", color: "text-brand-earth" },
    { label: "Laboratorios", desc: "Análisis clínicos y diagnóstico", href: "/directorio/health?cat=laboratorios", bg: "bg-brand-slate/10", color: "text-brand-slate" },
    { label: "Psicología", desc: "Psicólogos y salud mental", href: "/directorio/health?cat=psicologia", bg: "bg-brand-slate/10", color: "text-brand-slate" },
    { label: "Terapias alternativas", desc: "Kinesiología, acupuntura y más", href: "/directorio/health?cat=terapias", bg: "bg-brand-pine/10", color: "text-brand-pine" },
    { label: "Traslado de pacientes", desc: "Ambulancias y traslados", href: "/directorio/health?cat=traslado", bg: "bg-brand-slate/10", color: "text-brand-slate" },
    { label: "Todos", desc: "Ver todos los servicios de salud", href: "/directorio/health", bg: "bg-brand-sand/50", color: "text-brand-charcoal" },
  ],
  education: [
    { label: "Arte y Música", desc: "Talleres y conservatorios", href: "/directorio/education?cat=arte", bg: "bg-brand-earth/10", color: "text-brand-earth" },
    { label: "Colegios", desc: "Escuelas primarias y secundarias", href: "/directorio/education?cat=colegios", bg: "bg-brand-pine/10", color: "text-brand-pine" },
    { label: "Idiomas", desc: "Inglés, portugués y más", href: "/directorio/education?cat=idiomas", bg: "bg-brand-slate/10", color: "text-brand-slate" },
    { label: "Maestras/os Particulares", desc: "Apoyo escolar y tutorías", href: "/directorio/education?cat=maestras", bg: "bg-brand-earth/10", color: "text-brand-earth" },
    { label: "Todos", desc: "Ver toda la oferta educativa", href: "/directorio/education", bg: "bg-brand-sand/50", color: "text-brand-charcoal" },
  ],
  sports: [
    { label: "Fútbol", desc: "Escuelas y clubs", href: "/directorio/sports?cat=futbol", bg: "bg-brand-pine/10", color: "text-brand-pine" },
    { label: "Rugby", desc: "Clubs y escuelas de rugby", href: "/directorio/sports?cat=rugby", bg: "bg-brand-pine/10", color: "text-brand-pine" },
    { label: "Hockey", desc: "Clubs y escuelas de hockey", href: "/directorio/sports?cat=hockey", bg: "bg-brand-earth/10", color: "text-brand-earth" },
    { label: "Básquet", desc: "Clubs y escuelas de básquet", href: "/directorio/sports?cat=basquet", bg: "bg-brand-slate/10", color: "text-brand-slate" },
    { label: "Vóley", desc: "Clubes y escuelas de vóley", href: "/directorio/sports?cat=voley", bg: "bg-brand-pine/10", color: "text-brand-pine" },
    { label: "Handball", desc: "Clubs y escuelas de handball", href: "/directorio/sports?cat=handball", bg: "bg-brand-slate/10", color: "text-brand-slate" },
    { label: "Fausball", desc: "Clubes de fausball", href: "/directorio/sports?cat=fausball", bg: "bg-brand-earth/10", color: "text-brand-earth" },
    { label: "Pádel", desc: "Canchas y escuelas de pádel", href: "/directorio/sports?cat=padel", bg: "bg-brand-slate/10", color: "text-brand-slate" },
    { label: "Tenis", desc: "Escuelas y clubes de tenis", href: "/directorio/sports?cat=tenis", bg: "bg-brand-earth/10", color: "text-brand-earth" },
    { label: "Natación", desc: "Piletas y escuelas de natación", href: "/directorio/sports?cat=natacion", bg: "bg-brand-slate/10", color: "text-brand-slate" },
    { label: "Ciclismo", desc: "Cicloturismo y escuelas", href: "/directorio/sports?cat=ciclismo", bg: "bg-brand-earth/10", color: "text-brand-earth" },
    { label: "Trekking / Montaña", desc: "Senderismo y escalada", href: "/directorio/sports?cat=trekking", bg: "bg-brand-slate/10", color: "text-brand-slate" },
    { label: "Yoga / Pilates", desc: "Clases y estudios", href: "/directorio/sports?cat=yoga", bg: "bg-brand-pine/10", color: "text-brand-pine" },
    { label: "Gimnasio", desc: "Fitness y musculación", href: "/directorio/sports?cat=gimnasio", bg: "bg-brand-slate/10", color: "text-brand-slate" },
    { label: "Artes marciales", desc: "Judo, karate, box y más", href: "/directorio/sports?cat=artes-marciales", bg: "bg-brand-charcoal/10", color: "text-brand-charcoal" },
    { label: "Running", desc: "Grupos y entrenadores", href: "/directorio/sports?cat=running", bg: "bg-brand-earth/10", color: "text-brand-earth" },
    { label: "Todos", desc: "Ver todos los deportes", href: "/directorio/sports", bg: "bg-brand-sand/50", color: "text-brand-charcoal" },
  ],
  tourism: [
    { label: "Actividades y Paseos", desc: "Deportes y recreación", href: "/directorio/tourism?cat=actividades", bg: "bg-brand-pine/10", color: "text-brand-pine" },
    { label: "Agencia de Viajes", desc: "Paquetes y servicios", href: "/directorio/tourism?cat=agencia", bg: "bg-brand-slate/10", color: "text-brand-slate" },
    { label: "Alojamiento", desc: "Cabañas y hosterías", href: "/directorio/tourism?cat=alojamiento", bg: "bg-brand-pine/10", color: "text-brand-pine" },
    { label: "Alquiler", desc: "Autos, bicis y más", href: "/directorio/tourism?cat=alquiler", bg: "bg-brand-earth/10", color: "text-brand-earth" },
    { label: "Excursiones", desc: "Trekking y aventura", href: "/directorio/tourism?cat=excursiones", bg: "bg-brand-pine/10", color: "text-brand-pine" },
    { label: "Todos", desc: "Ver todo el turismo", href: "/directorio/tourism", bg: "bg-brand-sand/50", color: "text-brand-charcoal" },
  ],
  commerce: [
    { label: "Accesorios", desc: "Bijouterie, bolsos y complementos", href: "/directorio/commerce?cat=accesorios", bg: "bg-brand-earth/10", color: "text-brand-earth" },
    { label: "Fábrica de Espumantes", desc: "Producción y venta de espumantes", href: "/directorio/commerce?cat=fabrica-espumantes", bg: "bg-rose-100", color: "text-rose-700" },
    { label: "Forrajería", desc: "Alimentos y productos rurales", href: "/directorio/commerce?cat=forrajeria", bg: "bg-brand-earth/10", color: "text-brand-earth" },
    { label: "Hogar", desc: "Muebles y decoración", href: "/directorio/commerce?cat=hogar", bg: "bg-brand-earth/10", color: "text-brand-earth" },
    { label: "Imprenta", desc: "Impresión y diseño gráfico", href: "/directorio/commerce?cat=imprenta", bg: "bg-brand-slate/10", color: "text-brand-slate" },
    { label: "Indumentaria", desc: "Ropa y calzado", href: "/directorio/commerce?cat=indumentaria", bg: "bg-brand-slate/10", color: "text-brand-slate" },
    { label: "Inmobiliarias", desc: "Propiedades y alquileres", href: "/directorio/commerce?cat=inmobiliarias", bg: "bg-brand-pine/10", color: "text-brand-pine" },
    { label: "Mascotas", desc: "Tiendas para mascotas", href: "/directorio/commerce?cat=mascotas", bg: "bg-brand-pine/10", color: "text-brand-pine" },
    { label: "Niños", desc: "Artículos infantiles", href: "/directorio/commerce?cat=ninos", bg: "bg-brand-earth/10", color: "text-brand-earth" },
    { label: "Tecnología", desc: "Electrónica y celulares", href: "/directorio/commerce?cat=tecnologia", bg: "bg-brand-charcoal/10", color: "text-brand-charcoal" },
    { label: "Vehículos", desc: "Repuestos y accesorios", href: "/directorio/commerce?cat=vehiculos", bg: "bg-brand-slate/10", color: "text-brand-slate" },
    { label: "Veterinarias", desc: "Clínicas y tiendas veterinarias", href: "/directorio/commerce?cat=veterinarias", bg: "bg-brand-earth/10", color: "text-brand-earth" },
    { label: "Varios", desc: "Otros comercios del valle", href: "/directorio/commerce?cat=varios", bg: "bg-brand-sand/50", color: "text-brand-charcoal" },
    { label: "Todos", desc: "Ver todos los comercios", href: "/directorio/commerce", bg: "bg-brand-sand/50", color: "text-brand-charcoal" },
  ],
  events: [
    { label: "Culturales", desc: "Arte y exposiciones", href: "/directorio/events?cat=culturales", bg: "bg-brand-earth/10", color: "text-brand-earth" },
    { label: "Deportivos", desc: "Carreras y torneos", href: "/directorio/events?cat=deportivos", bg: "bg-brand-pine/10", color: "text-brand-pine" },
    { label: "Festivales", desc: "Oktoberfest y más", href: "/directorio/events?cat=festivales", bg: "bg-brand-earth/10", color: "text-brand-earth" },
    { label: "Gastronomía", desc: "Ferias y degustaciones", href: "/directorio/events?cat=gastronomia", bg: "bg-brand-earth/10", color: "text-brand-earth" },
    { label: "Infantiles", desc: "Para los más chicos", href: "/directorio/events?cat=infantiles", bg: "bg-brand-slate/10", color: "text-brand-slate" },
    { label: "Música", desc: "Recitales y peñas", href: "/directorio/events?cat=musica", bg: "bg-brand-slate/10", color: "text-brand-slate" },
    { label: "Varios", desc: "Otros eventos del valle", href: "/directorio/events?cat=varios", bg: "bg-brand-sand/50", color: "text-brand-charcoal" },
    { label: "Todos", desc: "Ver todos los eventos", href: "/directorio/events", bg: "bg-brand-sand/50", color: "text-brand-charcoal" },
  ],
  info: [
    { label: "Cooperativas", desc: "Luz, agua y gas", href: "/info-util?categoria=cooperativas", bg: "bg-brand-slate/10", color: "text-brand-slate" },
    { label: "Emergencias", desc: "Bomberos, policía, SAME", href: "/info-util?categoria=emergencias", bg: "bg-brand-earth/10", color: "text-brand-earth" },
    { label: "Farmacias de turno", desc: "Guardia 24hs", href: "/info-util?categoria=farmacias", bg: "bg-brand-pine/10", color: "text-brand-pine" },
    { label: "Veterinarias de turno", desc: "Guardia veterinaria", href: "/info-util?categoria=veterinarias", bg: "bg-brand-earth/10", color: "text-brand-earth" },
    { label: "Municipalidad", desc: "Trámites y contacto", href: "/info-util?categoria=municipalidad", bg: "bg-brand-pine/10", color: "text-brand-pine" },
    { label: "Transporte", desc: "Horarios de buses", href: "/info-util?categoria=transporte", bg: "bg-brand-slate/10", color: "text-brand-slate" },
    { label: "Turismo oficial", desc: "Oficinas de turismo", href: "/info-util?categoria=turismo", bg: "bg-brand-pine/10", color: "text-brand-pine" },
    { label: "Varios", desc: "Otra información útil", href: "/info-util?categoria=varios", bg: "bg-brand-sand/50", color: "text-brand-charcoal" },
    { label: "Todos", desc: "Ver toda la info útil", href: "/info-util", bg: "bg-brand-sand/50", color: "text-brand-charcoal" },
  ],
}

export type SectionKey = keyof typeof sectionCategories
