export const sectionCategories = {
  gastronomy: [
    { label: "Restaurantes", desc: "Cocina regional y menú del día", href: "/negocios?categoria=restaurant", bg: "bg-primary-100", color: "text-primary-500" },
    { label: "Cafés", desc: "Desayunos y meriendas", href: "/negocios?categoria=cafe", bg: "bg-accent-100", color: "text-accent-500" },
    { label: "Viandas", desc: "Comida casera para llevar", href: "/negocios?categoria=viandas", bg: "bg-blue-100", color: "text-blue-600" },
    { label: "Bares", desc: "Cervezas artesanales y copas", href: "/negocios?categoria=bar", bg: "bg-purple-100", color: "text-purple-600" },
    { label: "Delivery", desc: "Pedidos a domicilio", href: "/negocios?delivery=true", bg: "bg-green-100", color: "text-green-600" },
    { label: "Abierto ahora", desc: "Locales disponibles hoy", href: "/negocios?abierto=true", bg: "bg-yellow-100", color: "text-yellow-700" },
  ],
  services: [
    { label: "Plomería", desc: "Instalaciones y reparaciones", href: "/servicios?cat=plomeria", bg: "bg-blue-100", color: "text-blue-600" },
    { label: "Electricidad", desc: "Electricistas matriculados", href: "/servicios?cat=electricidad", bg: "bg-yellow-100", color: "text-yellow-700" },
    { label: "Gasista", desc: "Instalaciones de gas", href: "/servicios?cat=gasista", bg: "bg-accent-100", color: "text-accent-500" },
    { label: "Mecánica", desc: "Talleres y gomería", href: "/servicios?cat=mecanica", bg: "bg-stone-200", color: "text-stone-600" },
    { label: "Construcción", desc: "Albañilería y reformas", href: "/servicios?cat=construccion", bg: "bg-primary-100", color: "text-primary-500" },
    { label: "Pintor", desc: "Pintura interior y exterior", href: "/servicios?cat=pintor", bg: "bg-purple-100", color: "text-purple-600" },
    { label: "Herrero", desc: "Herrería y soldadura", href: "/servicios?cat=herrero", bg: "bg-red-100", color: "text-red-600" },
    { label: "Cerrajero", desc: "Cerraduras y llaves", href: "/servicios?cat=cerrajero", bg: "bg-green-100", color: "text-green-600" },
    { label: "Jardinero", desc: "Diseño y mantenimiento", href: "/servicios?cat=jardinero", bg: "bg-primary-100", color: "text-primary-500" },
    { label: "Piletero", desc: "Piletas y mantenimiento", href: "/servicios?cat=piletero", bg: "bg-blue-100", color: "text-blue-600" },
    { label: "Zinguero", desc: "Techos y canaletas", href: "/servicios?cat=zinguero", bg: "bg-stone-200", color: "text-stone-600" },
    { label: "Desinfecciones", desc: "Plagas y fumigaciones", href: "/servicios?cat=desinfecciones", bg: "bg-yellow-100", color: "text-yellow-700" },
    { label: "Perforaciones", desc: "Pozos de agua", href: "/servicios?cat=perforaciones", bg: "bg-accent-100", color: "text-accent-500" },
    { label: "Limpieza", desc: "Servicio doméstico", href: "/servicios?cat=limpieza", bg: "bg-purple-100", color: "text-purple-600" },
  ],
  health: [
    { label: "Clínicas y consultorios", desc: "Atención médica general", href: "/salud?cat=clinicas", bg: "bg-blue-100", color: "text-blue-600" },
    { label: "Farmacias", desc: "Farmacias del valle", href: "/salud?cat=farmacias", bg: "bg-green-100", color: "text-green-600" },
    { label: "Psicología", desc: "Atención psicológica", href: "/salud?cat=psicologia", bg: "bg-purple-100", color: "text-purple-600" },
    { label: "Odontología", desc: "Dentistas y ortodoncistas", href: "/salud?cat=odontologia", bg: "bg-yellow-100", color: "text-yellow-700" },
    { label: "Oftalmología", desc: "Oculistas y ópticas", href: "/salud?cat=oftalmologia", bg: "bg-accent-100", color: "text-accent-500" },
    { label: "Veterinarias", desc: "Para tus mascotas", href: "/salud?cat=veterinarias", bg: "bg-primary-100", color: "text-primary-500" },
    { label: "Emergencias", desc: "Guardias y urgencias", href: "/salud?cat=emergencias", bg: "bg-red-100", color: "text-red-600" },
  ],
  education: [
    { label: "Colegios", desc: "Escuelas primarias y secundarias", href: "/educacion?cat=colegios", bg: "bg-blue-100", color: "text-blue-600" },
    { label: "Institutos", desc: "Terciarios y universitarios", href: "/educacion?cat=institutos", bg: "bg-primary-100", color: "text-primary-500" },
    { label: "Idiomas", desc: "Inglés, portugués y más", href: "/educacion?cat=idiomas", bg: "bg-accent-100", color: "text-accent-500" },
    { label: "Maestras particulares", desc: "Apoyo escolar y tutorías", href: "/educacion?cat=maestras", bg: "bg-purple-100", color: "text-purple-600" },
    { label: "Arte y música", desc: "Talleres y conservatorios", href: "/educacion?cat=arte", bg: "bg-yellow-100", color: "text-yellow-700" },
    { label: "Deportes", desc: "Escuelas deportivas", href: "/educacion?cat=deportes", bg: "bg-green-100", color: "text-green-600" },
  ],
  tourism: [
    { label: "Alojamiento", desc: "Cabañas y hosterías", href: "/turismo?cat=alojamiento", bg: "bg-primary-100", color: "text-primary-500" },
    { label: "Excursiones", desc: "Trekking y aventura", href: "/turismo?cat=excursiones", bg: "bg-green-100", color: "text-green-600" },
    { label: "Camping", desc: "Campings del valle", href: "/turismo?cat=camping", bg: "bg-accent-100", color: "text-accent-500" },
    { label: "Actividades", desc: "Deportes y recreación", href: "/turismo?cat=actividades", bg: "bg-blue-100", color: "text-blue-600" },
    { label: "Alquiler", desc: "Autos, bicis y más", href: "/turismo?cat=alquiler", bg: "bg-yellow-100", color: "text-yellow-700" },
    { label: "Guías", desc: "Guías locales del valle", href: "/turismo?cat=guias", bg: "bg-purple-100", color: "text-purple-600" },
  ],
  commerce: [
    { label: "Almacenes", desc: "Mercados y despensas", href: "/comercios?cat=almacenes", bg: "bg-primary-100", color: "text-primary-500" },
    { label: "Dietéticas", desc: "Productos naturales", href: "/comercios?cat=dieteticas", bg: "bg-green-100", color: "text-green-600" },
    { label: "Ropa", desc: "Indumentaria y calzado", href: "/comercios?cat=ropa", bg: "bg-purple-100", color: "text-purple-600" },
    { label: "Artesanías", desc: "Productos regionales", href: "/comercios?cat=artesanias", bg: "bg-accent-100", color: "text-accent-500" },
    { label: "Ferreterías", desc: "Materiales y herramientas", href: "/comercios?cat=ferreterias", bg: "bg-stone-200", color: "text-stone-600" },
    { label: "Otros", desc: "Más comercios del valle", href: "/comercios", bg: "bg-yellow-100", color: "text-yellow-700" },
  ],
  events: [
    { label: "Festivales", desc: "Oktoberfest y más", href: "/eventos?cat=festivales", bg: "bg-accent-100", color: "text-accent-500" },
    { label: "Gastronomía", desc: "Ferias y degustaciones", href: "/eventos?cat=gastronomia", bg: "bg-primary-100", color: "text-primary-500" },
    { label: "Música", desc: "Recitales y peñas", href: "/eventos?cat=musica", bg: "bg-purple-100", color: "text-purple-600" },
    { label: "Deportivos", desc: "Carreras y torneos", href: "/eventos?cat=deportivos", bg: "bg-blue-100", color: "text-blue-600" },
    { label: "Culturales", desc: "Arte y exposiciones", href: "/eventos?cat=culturales", bg: "bg-yellow-100", color: "text-yellow-700" },
    { label: "Infantiles", desc: "Para los más chicos", href: "/eventos?cat=infantiles", bg: "bg-green-100", color: "text-green-600" },
  ],
  info: [
    { label: "Emergencias", desc: "Bomberos, policía, SAME", href: "/info?cat=emergencias", bg: "bg-red-100", color: "text-red-600" },
    { label: "Farmacias de turno", desc: "Guardia 24hs", href: "/info?cat=farmacias", bg: "bg-green-100", color: "text-green-600" },
    { label: "Municipalidad", desc: "Trámites y contacto", href: "/info?cat=municipalidad", bg: "bg-blue-100", color: "text-blue-600" },
    { label: "Cooperativas", desc: "Luz, agua y gas", href: "/info?cat=cooperativas", bg: "bg-yellow-100", color: "text-yellow-700" },
    { label: "Transporte", desc: "Horarios de buses", href: "/info?cat=transporte", bg: "bg-accent-100", color: "text-accent-500" },
    { label: "Turismo oficial", desc: "Oficinas de turismo", href: "/info?cat=turismo", bg: "bg-primary-100", color: "text-primary-500" },
  ],
}

export type SectionKey = keyof typeof sectionCategories